services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION}
    container_name: gymkana_n8n
    restart: unless-stopped
    environment:
      NODE_ENV: production
      N8N_HOST: ${N8N_EDITOR_DOMAIN}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      N8N_EDITOR_BASE_URL: https://${N8N_EDITOR_DOMAIN}/
      N8N_WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_PROXY_HOPS: 1
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-service-account.json
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: none
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 168
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./secrets/firebase-service-account.json:/run/secrets/firebase-service-account.json:ro
    networks:
      - proxy-network


networks:
  proxy-network:
    external: true
